### ISSUE TITLE
APPHelloWorld01 无法运行

### ISSUE THREAD

**Issue by JackyLee3362** [Simba-cheng/ApacheCamelDemo#200]
APPHelloWorld01 类中，message 没有 getBody() 方法，应该如何解决？

<img width="950" alt="image" src="https://github.com/Simba-cheng/ApacheCamelDemo/assets/53095830/9c82bbaa-4358-468c-b5b4-e82b8f8902bf">

**Comment by Simba-cheng** [comment]
检查了下，由于之前 dependabot 提示升级，错误升级了 camel-core 版本，没有编译就更新，导致兼容性问题。
请你将 camel-core 版本修改为 2.24.0。
这个问题我也会同步修复，感谢提醒。
